application: apothem100
version: 103
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images

- url: /bootstrap
  static_dir: bootstrap

- url: /css
  static_dir: css

- url: /javaScript_files
  static_dir: javaScript_files

- url: /csv_files
  static_dir: csv_files
  application_readable: True

- url: .*
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin


libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6" 

builtins:
- deferred: on